### PR TITLE
Python Factorial Recursive

### PR DESCRIPTION
**Pull request by TheUltimateRythimGamer**
A recursive solution to Factorial problem in python
Happy Hacktober

### CODE REVIEW

**Comment by AakashBelide** [comment]
> 
> 
> A recursive solution to Factorial problem in python
> Happy Hacktober

Kindly check the correction made and commit the changes made accordingly.

**Comment by TheUltimateRythimGamer** [comment]
thnxs, but i wanna print the number in every interaction

**Comment by AakashBelide** [comment]
> 
> 
> thnxs, but i wanna print the number in every interaction

In that case, you can edit your code accordingly and commit the changes and inform them here by commenting. The previous code didn't actually give the output according to what you're trying to say. When I provide an input number, for example, 5, the output is as follows: 5, 4, 3, 2, 1 (Prints each of the number in a different line)

**Comment by TheUltimateRythimGamer** [comment]
oh, You're right, but don't Worry, the change is good to me. nwn

**Comment by AakashBelide** [comment]
Okay. If you want to make any changes, you can do it.

**Pull request merged**
